import type { Express, Response } from "express";
import { z } from "zod";
import { DatabaseManager } from "../../../../packages/database/src/index";
import { activeField, audit, normalizeActive, nullableText, positiveId, requirePermission, text, type AuthenticatedRequest, validateCompanyAccess } from "./common";

const schema=z.object({company_id:positiveId,element_id:positiveId,code:text(2,40),name:text(2,180),nature:z.enum(["INGRESO","COSTO","GASTO","ACTIVO","PASIVO","PATRIMONIO"]),movement_type:z.enum(["DETALLE","ACUMULADORA"]).optional(),description:nullableText(),active:activeField});

export function registerAccountRoutes(app:Express,database:DatabaseManager){
  app.get("/api/catalog/cuentas",requirePermission("ESTRUCTURA:LEER"),(request:AuthenticatedRequest,response:Response)=>{const companyId=Number(request.query.company_id||request.identity!.companyId);validateCompanyAccess(request.identity!,companyId);response.json(database.connection.prepare("SELECT * FROM budget_accounts WHERE company_id=? ORDER BY code").all(companyId));});
  app.post("/api/catalog/cuentas",requirePermission("ESTRUCTURA:CREAR"),(request:AuthenticatedRequest,response:Response)=>{const input=schema.parse(request.body);validateCompanyAccess(request.identity!,input.company_id);if(!database.connection.prepare("SELECT id FROM budget_elements WHERE id=? AND company_id=?").get(input.element_id,input.company_id)){response.status(400).json({code:"INVALID_ELEMENT",message:"El elemento no pertenece a la empresa activa."});return;}const stamp=new Date().toISOString();const result=database.connection.prepare("INSERT INTO budget_accounts (company_id,element_id,code,name,nature,movement_type,description,active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").run(input.company_id,input.element_id,input.code,input.name,input.nature,input.movement_type??"DETALLE",input.description??null,normalizeActive(input.active??1),stamp,stamp);const id=Number(result.lastInsertRowid);audit(database,request.identity!,"CREAR","budget_accounts",id,input.company_id,`Cuenta ${input.name} creada.`,undefined,input);response.status(201).json({id,message:"Cuenta creada correctamente."});});
  app.patch("/api/catalog/cuentas/:id",requirePermission("ESTRUCTURA:EDITAR"),(request:AuthenticatedRequest,response:Response)=>{const id=Number(request.params.id);const input=schema.partial().parse(request.body);const before=database.connection.prepare("SELECT * FROM budget_accounts WHERE id=?").get(id) as Record<string,unknown>|undefined;if(!before){response.status(404).json({code:"NOT_FOUND",message:"Cuenta no encontrada."});return;}const companyId=Number(input.company_id??before.company_id);validateCompanyAccess(request.identity!,companyId);const values={...before,...input,active:normalizeActive(input.active??before.active)} as Record<string,unknown>;if(!database.connection.prepare("SELECT id FROM budget_elements WHERE id=? AND company_id=?").get(values.element_id,companyId)){response.status(400).json({code:"INVALID_ELEMENT",message:"El elemento no pertenece a la empresa activa."});return;}database.connection.prepare("UPDATE budget_accounts SET company_id=?,element_id=?,code=?,name=?,nature=?,movement_type=?,description=?,active=?,updated_at=? WHERE id=?").run(values.company_id,values.element_id,values.code,values.name,values.nature,values.movement_type,values.description,values.active,new Date().toISOString(),id);audit(database,request.identity!,"EDITAR","budget_accounts",id,companyId,"Cuenta actualizada.",before,values);response.json({message:"Cuenta actualizada correctamente."});});
  app.delete("/api/catalog/cuentas/:id",requirePermission("ESTRUCTURA:ELIMINAR"),(request:AuthenticatedRequest,response:Response)=>{const id=Number(request.params.id);const before=database.connection.prepare("SELECT * FROM budget_accounts WHERE id=?").get(id) as Record<string,unknown>|undefined;if(!before){response.status(404).json({code:"NOT_FOUND",message:"Cuenta no encontrada."});return;}validateCompanyAccess(request.identity!,Number(before.company_id));database.connection.prepare("UPDATE budget_accounts SET active=0,updated_at=? WHERE id=?").run(new Date().toISOString(),id);audit(database,request.identity!,"ELIMINAR","budget_accounts",id,Number(before.company_id),"Cuenta desactivada.",before,{...before,active:0});response.json({message:"Cuenta desactivada correctamente."});});
}
